stages:
  - build
  - deploy

build alert:
  script:
    - ls
    - docker build -f Dockerfile.agent -t dockernj.baozou.com/nanjing/alertagent:latest --rm .
    - docker push dockernj.baozou.com/nanjing/alertagent:latest
    - docker build -f Dockerfile.server -t dockernj.baozou.com/nanjing/alertserver:latest --rm .
    - docker push dockernj.baozou.com/nanjing/alertserver:latest
  stage: build
  tags:
    - nj_go_build
  only:
    - master

deploy alert:
  script:
    - cd ./ansible && ansible-playbook -i config/hosts deployagent.yml -e "SERVER_URL=10.4.5.62:50075"
    - ansible-playbook -i config/hosts deployserver.yml -e "SERVER_Token=https://hooks.slack.com/services/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 SERVER_CHANNEL=#test SERVER_USERNAME=BombChecker SERVER_PORT=50075"
  stage: deploy
  tags:
    - nj-lucy-deploy
  only:
  - deploy
