stages:
  - build
  - deploy

build alert:
  script:
    - docker build -f Dockerfile.agent -t xx.xx.com/xx/alertagent:latest --rm .
    - docker push xx.xx.com/xx/alertagent:latest
    - docker build -f Dockerfile.server -t xx.xx.com/xx/alertserver:latest --rm .
    - docker push xx.xx.com/xx/alertserver:latest
  stage: build
  tags:
    - nj_go_build
  only:
    - master

deploy alert:
  script:
    - cd ./ansible && ansible-playbook -i config/hosts deployagent.yml -e "SERVER_URL=10.4.5.62:50075"
    - ansible-playbook -i config/hosts deployserver.yml -e "SERVER_TOKEN=https://hooks.slack.com/services/xxxxx/xxxx/xxxx SERVER_CHANNEL=#test SERVER_USERNAME=BombChecker SERVER_PORT=50075"
  stage: deploy
  tags:
    - nj-lucy-deploy
  only:
    - deploy
