stages:
  - build
  - deploy

build alert:
  script:
    - docker build -f Dockerfile.agent -t dockernj.baozou.com/nanjing/alertagent:latest --rm .
    - docker push dockernj.baozou.com/nanjing/alertagent:latest
  stage: build
  tags:
    - nj_go_build
  only:
    - master

deploy alert:
  script:
    - cd ./ansible && ansible-playbook -i config/hosts deployagent.yml -e "SERVER_URL=10.4.5.62"
  stage: deploy
  tags:
    - nj-lucy-deploy
  only:
  - deploy