# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.

FROM dockernj.baozou.com/nanjing/alpine-golang

# Copy the local package files to the container's workspace.
COPY ./ /go

WORKDIR /go
# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN /go/bin/gb build agent

# Run the outyet command by default when the container starts.
CMD /go/bin/agent
